<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1010a0b68656c6c6f2e70726f746f12077365727669636522170a0752" .
            "657175657374120c0a046e616d6518012001280922180a055265706c7912" .
            "0f0a076d657373616765180120012809326e0a0747726565746572122e0a" .
            "0853617948656c6c6f12102e736572766963652e526571756573741a0e2e" .
            "736572766963652e5265706c79220012330a0d53617948656c6c6f416761" .
            "696e12102e736572766963652e526571756573741a0e2e73657276696365" .
            "2e5265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

